# Copyright (c) 2017 ~ 2025, the original author wangl.sir individual Inc,
# All rights reserved. Contact us <Wanglsir@gmail.com, 983708408@qq.com>
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

#
# #### Spring Boot Infra core configuration. ####
#

# Global error handling configuration.
spring:
  ## Starting banner configuration.
  banner:
    charset: UTF-8
    #location: classpath:default-banner.txt
  #infra:
  #  core:
  #    bootstrapping:
  #      enabled: true ## Default by true
  #    naming-beanfactory:
  #      enabled: true ## Default by true
  #    generic-operator:
  #      enabled: true ## Default by true
  #    smart-proxies:
  #      enabled: true ## Default by true
  #      base-packages: ## Default by '*'
  #    logging:
  #      ## If this switch is enabled, then check whether the request header and parameters meet the current conditions for printing flight logs.
  #      ## If so, print according to the predetermined level, otherwise do not print. If this switch is set to false, printing logs will be
  #      ## permanently disabled (regardless of the request header). and whether the parameters meet the conditions).
  #      enabled: false ## Default by false
  #      ## It is used to set the execution order of the filter bean. Note: Setting this value to a small or large value will affect the behavior.
  #      ## For example, if it is set to Ordered.HIGHEST_PRECEDENCE (after the authentication filter), the principal can be printed to the log,
  #      ## otherwise it will not be available. principal value.
  #      filterOrder: 0 ## Default by 0
  #      ## The output default level of flight log printing, similar to kubectl design value range: 1-10, 1 is coarse-grained log, 10 is the most fine-grained log.
  #      defaultVerboseLevel: 10 ## Default by 10
  #      ## The request header name used to set the log output verbose level valid only for the current request, This value takes precedence over '#defaultVerboseLevel'
  #      verboseLevelRequestHeader: X-Log-Level ## Default by 'X-Log-Level'
  #      ## In order to prevent the request body data from being too large, only the
  #      ## first small part of the body data is obtained.
  #      maxPrintRequestBodyLength: 1024 ## Default by 1024
  #      ## In order to prevent the response body data from being too large, only the
  #      ## first small part of the body data is obtained.
  #      maxPrintResponseBodyLength: 1024 ## Default by 1024
  #      ## Prefer to enable print logs match SPEL match expression. Default by '#{true}', which means never match.
  #      preferOpenMatchExpression: '#{$defaultLogHeader.or($defaultLogQuery).or($apiLogPath).test($request)}'
  #      ## Prefer to enable print logs match rules definition.
  #      preferMatchRuleDefinitions:
  #        - name: defaultLogHeader
  #          #method:
  #          #schema:
  #          #host:
  #          #port:
  #          #path: ## Ant path pattern.
  #          header:
  #            symbol: IGNORECASE_EQ ## Options(eq|prefix|suffix|include|ignorecase_eq|ignorecase_prefix|ignorecase_suffix|ignorecase_include)
  #            key: X-${spring.application.name}-Log
  #            value: y
  #          #cookie:
  #          #  symbol:
  #          #  key:
  #          #  value:
  #          #query:
  #          #  symbol:
  #          #  key:
  #          #  value:
  #        - name: defaultLogQuery
  #          query:
  #            symbol: IGNORECASE_EQ
  #            key: __${spring.application.name}_log
  #            value: y
  #        - name: apiLogPath
  #          path: '/api/**'
  #    trace:
  #      enabled: false ## Default by false
  #    web:
  #      human-date-converter:
  #        enabled: true ## Default by true
  #      embedded-webapps:
  #        enabled: false ## Default by false
  #        base-uri: /default-view
  #        webapp-location: classpath*:/default-webapps
  #      global-error:
  #        enabled: true ## Default by true
  #        base-path: /default-error-view/
  #        ## Default for empty, The default is to intercept the domain name of the browser address bar.
  #        home-uri: 'javascript:location.href=location.origin'
  #        ## Rendering template path or redirect URI on exception,
  #        ## for example: redirect:http://domain.com/404.html or /404.tpl.html
  #        rendering-mapping:
  #           403: 403.tpl.html
  #           404: 404.tpl.html
  #           500: 50x.tpl.html
  #           501: 50x.tpl.html
  #           502: 50x.tpl.html
  #           503: 50x.tpl.html
