# Copyright (c) 2017 ~ 2025, the original authors individual Inc,
# All rights reserved. Contact us James Wong <jameswong1376@gmail.com>
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

Args = --initialize-at-build-time=com.fasterxml.jackson.annotation.JsonProperty$Access \
       --initialize-at-build-time=org.apache.commons.lang3.RandomUtils \
       --initialize-at-build-time=org.apache.commons.lang3.RandomStringUtils \
       --initialize-at-run-time=org.apache.commons.dbcp2.ObjectNameWrapper \
       --initialize-at-run-time=org.apache.commons.dbcp2.PoolableConnection \
       --initialize-at-run-time=org.apache.sshd.common.config.keys.loader.openssh.OpenSSHKeyPairResourceParser \
       --initialize-at-run-time=org.apache.sshd.common.config.keys.KeyUtils \
       --initialize-at-run-time=org.apache.sshd.common.util.security.eddsa.Ed25519PublicKeyDecoder \
       --initialize-at-run-time=groovy.grape.GrapeIvy \
       --initialize-at-run-time=com.wl4g.infra.common.resource.VfsUtils2 \
       --trace-class-initialization=java.lang.Thread \
       --trace-class-initialization=io.netty.util.concurrent.GlobalEventExecutor \
       --trace-class-initialization=io.netty.util.concurrent.ScheduledFutureTask \
       --trace-class-initialization=org.apache.sshd.common.util.security.SecurityUtils \
       --trace-object-instantiation=java.util.Random \
       --trace-object-instantiation=java.security.SecureRandom \
       --trace-object-instantiation=com.sun.jmx.mbeanserver.JmxMBeanServer